version: '3.4'

services:
  localstack:
    build: ./localstack/
    shm_size: '512mb'
    ports:
      - '4566:4566'
    environment:
      - NO_PROXY=${NO_PROXY:-localhost}
      - HOSTNAME=localstack
      - EXTERNAL_HOSTNAME=localstack
      - SERVICES=sns,s3,sqs,dynamodb,lambda,kinesis
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - TMPDIR=/tmp
      - LAMBDA_REMOTE_DOCKER=true  # Required for local dist mounting lambdas
      - KINESIS_PROVIDER=kinesalite # might be required for m1 macs, seems to remove JDK dependency
      - LAMBDA_DOCKER_NETWORK=testing_default # Required for lambda -> other containers connection
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

